-- 통합이니까 UNION ALL
-- UNION ALL 할 때 데이터가 없는 경우 NULL을 채우고 싶다면 'NULL AS 칼럼명'

SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM
(
    SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
)
    UNION ALL
(
    SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
)
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID 