-- FETCH FIRST 숫자 ROWS ONLY;에 익숙해지기
SELECT AI.NAME, AI.DATETIME
FROM ANIMAL_INS AI LEFT OUTER JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.DATETIME IS NULL
ORDER BY AI.DATETIME
FETCH FIRST 3 ROWS ONLY;