-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    --8~10월 중 총 5회 이상 대여된 CAR_ID
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
      WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10' 
      GROUP BY CAR_ID
      HAVING COUNT(*) >= 5
) AND TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
-- 월별, 차량별 그룹화
GROUP BY TO_CHAR(START_DATE, 'MM'), CAR_ID
ORDER BY MONTH, CAR_ID DESC;