-- 1. 거래가 완료된(DONE) 회원 -> WHERE 절
-- 2. 완료된 회원 중 총 거래 금액이 700,000원 이상인 회원 -> GROUP BY ~ HAVING 절
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_USER U
     ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY U.USER_ID, U.NICKNAME
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES;